from machine import Pin
from time import sleep
led_0 = Pin(0, Pin.OUT)
led_1 = Pin(1, Pin.OUT)
led_2 = Pin(2, Pin.OUT)
led_3 = Pin(3, Pin.OUT)
led_4 = Pin(4, Pin.OUT)
led_5 = Pin(5, Pin.OUT)
led_6 = Pin(6, Pin.OUT)
led_7 = Pin(7, Pin.OUT)
led_8 = Pin(8, Pin.OUT)
led_9 = Pin(9, Pin.OUT)
led_10 = Pin(10, Pin.OUT)
led_11 = Pin(11, Pin.OUT)
led_12 = Pin(12, Pin.OUT)
led_13 = Pin(13, Pin.OUT)
led_14 = Pin(14, Pin.OUT)
led_15 = Pin(15, Pin.OUT)
TIME_SLEEP = .1 # 1 second
i = 10
while i > 0:
    led_0.on()
    sleep(1)
    led_0.off()
    sleep(1)
    led_1.on()
    sleep(1)
    led_1.off()
    sleep(1)
    led_2.on()
    sleep(1)
    led_2.off()
    sleep(1)
    led_3.on()
    sleep(1)
    led_3.off()
    sleep(1)
    led_4.on()
    sleep(1)
    led_4.off()
    sleep(1)
    led_5.on()
    sleep(1)
    led_5.off()
    sleep(1)
    led_6.on()
    sleep(1)
    led_6.off()
    sleep(1)
    led_7.on()
    sleep(1)
    led_7.off()
    sleep(1)
    led_8.on()
    sleep(1)
    led_8.off()
    sleep(1)
    led_9.on()
    sleep(1)
    led_9.off()
    sleep(1)
    led_10.on()
    sleep(1)
    led_10.off()
    sleep(1)
    led_11.on()
    sleep(1)
    led_11.off()
    sleep(1)
    led_12.on()
    sleep(1)
    led_12.off()
    sleep(1)
    led_13.on()
    sleep(1)
    led_13.off()
    sleep(1)
    led_14.on()
    sleep(1)
    led_14.off()
    sleep(1)
    led_15.on()
    sleep(1)
    led_15.off()
    sleep(1)
    i -= 1

